extensions:
  dx/excshell/1:
    operations:
      view:
        - type: web
          impl: index.html
    web-src: src/
    runtimeManifest:
      packages:
        aem-component-usage-analytics:
          license: Apache-2.0
          actions:
            queryComponents:
              function: actions/queryComponents.js
              web: 'yes'
              runtime: nodejs18
              limits:
                timeout: 120000
                memory: 1024
              inputs:
                AEM_AUTHOR_BASE_URL: $AEM_AUTHOR_BASE_URL
                AEM_BASE_URL: $AEM_BASE_URL
                AEM_CONTENT_PATH: $AEM_CONTENT_PATH
                AEM_APPS_PATH: $AEM_APPS_PATH
                IMS_CLIENT_ID: $IMS_CLIENT_ID
                IMS_CLIENT_SECRET: $IMS_CLIENT_SECRET
                IMS_ORG_ID: $IMS_ORG_ID
                IMS_SCOPES: $IMS_SCOPES
                IMS_TECHNICAL_ACCOUNT_ID: $IMS_TECHNICAL_ACCOUNT_ID
              annotations:
                require-adobe-auth: true